### ISSUE TITLE
Trouble with printing the images as pdf

### ISSUE THREAD

**Issue by GianfrancoVieri** [BrianChung10/SOP#10]
Hi, @dlfivefifty @ioannisPApapadopoulos , may I know how to get the julia plots in visual studio code as pdfs instead of png? We tried printing the png and convert it to pdf but the image quality is bad. Is there any other way where we can directly let julia plot our graphs in pdfs instead of png?
Thanks!

**Comment by ioannisPApapadopoulos** [comment]
How are you saving the plots? save it with a .pdf extension instead of .png

**Comment by GianfrancoVieri** [comment]
I save it in the visual studio code and it has only option of saving it as .png , I am not sure how to save it with a .pdf extension though?

**Comment by ioannisPApapadopoulos** [comment]
`p =plot(...)
savefig(p,"plot.pdf")`

**Comment by GianfrancoVieri** [comment]
hi @ioannisPApapadopoulos, yeah I think it works now, thanks a lot John.

**Comment by fz920** [comment]
I tried to save the plots as plot.pdf, but I cannot open the file with some strange
