### ISSUE TITLE
Deflation formula for nonlinear systems in M2R2022 -- DimensionMismatch

### ISSUE THREAD

**Issue by fz920** [BrianChung10/SOP#4]
![image](https://user-images.githubusercontent.com/97394947/171207601-2a34ef91-0ef0-4305-ba9c-588cadf3e34f.png)
Hi during my implementation of the deflated Newton via (2.10), I kept getting the DimensionMismatch error, and I think there is something wrong with this formula. Could you tell me where goes wrong? Thanks!

**Comment by GianfrancoVieri** [comment]
Hi, I think the function "deflated_newton_2" in finite_difference_G.jl under simple deflation solves the above problem but I am not sure if it is valid. I let M be a scalar operator instead of a matrix, would that be alright?

**Comment by ioannisPApapadopoulos** [comment]
Yep, so instead of the identity, use the scalar 1. Then, m would map from R^n to R and would be a scalar.
