### ISSUE TITLE
Goal 9: Relevance of Kronecker Product

### ISSUE THREAD

**Issue by BrianChung10** [BrianChung10/SOP#8]
I don't understand how the matrix in 4.5 can be constructed using Kronecker product at all. What sort of additional manipulations should there be?

**Comment by fz920** [comment]
Hi, @dlfivefifty @ioannisPApapadopoulos could you help with this question? Thanks!

**Comment by ioannisPApapadopoulos** [comment]
From memory, the idea is to construct the 1D finite difference matrix (2 on the diagonal and -1 on the subdiagonals) then use kron to construct the 2D finite difference matrix.

First link on Google when searching 2d finite difference Kronecker product gives this https://math.mit.edu/~stevenj/18.303/lecture-10.html

There might be more useful pages elsewhere too

**Comment by fz920** [comment]
> @BrianChung10 @fz920 I wanted to add (since my document might not have made it clear) the current implementation in `Finite_Differences_2D/Goal_9.jl ` of the 2D finite difference matrix is not correct. It is correct for `n=4` but for higher values of `n` the gap between the first and second subdiagonals of -1 increases. For `n=4` that gap is one entry but that's specific to `n=4`. The gap is determined by the value of `n` and the lexicographic ordering.

Thank you for pointing that out. I have modifed the codes in `Finite_Differences_2D/Goal_9.jl`.

**Comment by ioannisPApapadopoulos** [comment]
Looks good! Glad you got the `kron` working! Is there a reason why the RHS is `f(x, y) = 2π^2 * sin(π * x)cos(π * y)` in line 19 rather than `f(x, y) = 2π^2 * sin(π * x)sin(π * y)`?

**Comment by fz920** [comment]
> Looks good! Glad you got the `kron` working! Is there a reason why the RHS is `f(x, y) = 2π^2 * sin(π * x)cos(π * y)` in line 19 rather than `f(x, y) = 2π^2 * sin(π * x)sin(π * y)`?

Oh, I misread the formula in the pdf😂. Fixed it.

By the way, do you think the diagram produced is the right contour plot for the poisson equation?
<img width="738" alt="Screen Shot 2022-06-07 at 13 30 27" src="https://user-images.githubusercontent.com/97394947/172379158-b3e1d229-a214-413e-99d9-6c727a599e72.png">

**Comment by ioannisPApapadopoulos** [comment]
The reason I chose that right-hand side is because it's possible to guess what the solution is. The right-hand side satisfies the boundary conditions by design and then the solution is almost equal the right-hand side modulo a constant. 

So if you work out the constant, you can do a direct comparison! (You can even measure the difference in the numerical and actual solutions to compute the error).

**Comment by fz920** [comment]
> The reason I chose that right-hand side is because it's possible to guess what the solution is. The right-hand side satisfies the boundary conditions by design and then the solution is almost equal to the right-hand side modulo a constant.
> 
> So if you work out the constant, you can do a direct comparison! (You can even measure the difference in the numerical and actual solutions to compute the error).

Thank you for your suggestion. I am guessing the general form of the actual solution should be u(x, y) = sin(pi x)sin(pi y) + c1x + c2y + c3, and by applying the boundary condition to this equation, the actual solution should be u(x, y) = sin(pi x)sin(pi y)?

I have worked out the contour for u which looks quite similar as the contour of the numerical solution, and the only difference is that the center of the contour of u is brighter.

The norm of the difference between the acutal solution and the numerical solution is approximately 0.00411 which is reasonable I think.

**Comment by fz920** [comment]
Hi I just found an error in my function `fd_2d` in the `Finite_Difference_2D/Goal_9&10`. The function computes the matrix as below
<img width="383" alt="Screen Shot 2022-06-08 at 13 45 44" src="https://user-images.githubusercontent.com/97394947/172619672-927cdb39-0261-4d14-ab25-6cb6d4f107ba.png">
and the [4, 3] entry should be -1 instead of 0. Do you know why I get this error?

**Comment by dlfivefifty** [comment]
Why do you think there should be a -1 there?

**Comment by fz920** [comment]
<img width="1209" alt="Screen Shot 2022-06-08 at 21 18 06" src="https://user-images.githubusercontent.com/97394947/172709237-7b41a792-78c3-44d9-800f-197e2e98e8ac.png">
Hi, @dlfivefifty this is the matrix given in the pdf, and the entires below the diagonal should all be -1. Is there a typo in this matrix?

**Comment by dlfivefifty** [comment]
Yes

**Comment by fz920** [comment]
Thanks! It works
